### PR TITLE
importing exceptions now works

### PR DESCRIPTION
**Pull request by ingobecker**
Your upstream python package is broken. If i import the controller module it throws an exception because there is no package called `exceptions`. I fixed the import statement in your `controller` module.

### CODE REVIEW

**Comment by jcormier** [comment]
Any status on this?

**Comment by jcormier** [comment]
```
----> 1 from unifi import controller

~/.local/share/virtualenvs/unifi-cl-inout-fqV-B3bk/lib/python3.5/site-packages/unifi/controller.py in <module>
     14 urllib3.disable_warnings()
     15
---> 16 import exceptions
     17
     18

ImportError: No module named 'exceptions'
```

**Comment by ingobecker** [comment]
I fixed it in my fork. If you just need a fast working solution and don't want to wait until it is merged use my fork. But i think there are a lot more issues with this library and it feels incomplete, just as a word of warning.

**Comment by jcormier** [comment]
That's fine. I just need it to get the connected clients.  And its working so far.

**Comment by fgbs** [comment]
sorry guys for my lack of response

**Pull request merged**
